name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Web Version/requirements_web.txt
        pip install -r Console Version/requirements.txt

    - name: Test with pytest
      run: |
        cd Web Version
        python -m pytest

    - name: Check code style
      run: |
        cd Web Version
        pip install flake8
        flake8 .
