name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install root dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Web version dependencies
      run: |
        cd "Web Version"
        pip install -r requirements_web.txt

    - name: Install Console version dependencies
      run: |
        cd "Console Version"
        pip install -r requirements.txt

    - name: Test Web version
      run: |
        cd "Web Version"
        python -m pytest --cov=app --cov-report=term-missing

    - name: Check code style
      run: |
        cd "Web Version"
        pip install flake8
        flake8 .

    - name: Run Web version
      run: |
        cd "Web Version"
        python app.py
